### ISSUE TITLE
ConnectionRefusedError: [WinError 10061]

### ISSUE THREAD

**Issue by bemxio** [ev3dev-python-tools/thonny-ev3dev#1]
**What are you trying to do?**

I am trying to run the script in the shell

**What did you expect to happen**

The program should have play sound

**What actually happened**

The program did traceback and the error i mentioned in title

**Source Code**

Here is the program I am trying to run.
```
#!/usr/bin/env python3
from ev3dev2.sound import Sound

sound = Sound()
sound.speak('Welcome to the E V 3 dev project!')
```
**Screenshots**
None

**Desktop**:
OS and version: Windows 10 1903
Connection Type: USB
Software: Thonny, PuTTY

**Robot**
Device: EV3
Versions: [see below - SD card image version, Linux kernel version, etc.]
```
Image file:         ev3dev-stretch-ev3-generic-2019-10-23
Kernel version:     4.14.117-ev3dev-2.3.4-ev3
Brickman:           0.10.2
BogoMIPS:           148.88
Bluetooth:
Board:              board0
BOARD_INFO_HW_REV=8
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=7
BOARD_INFO_SERIAL_NUM=0016537F7FF1
BOARD_INFO_TYPE=main
```
**Background Information**
I am trying to make a script that runs in shell and communicates from the shell to EV3 because I want to build remote control for my EV3 robotic hand

**Comment by harcokuppens** [comment]
You get a ConnectionRefusedError exception which means something is wrong with the connection from your windows pc to the ev3. 
To setup the connection you have to do two things:

- install ev3dev os on a sdcard and  install it on the ev3 and reboot the ev3, it wil automatically boot the ev3dev os. For instructions see the wiki page https://github.com/ev3dev-python-tools/thonny-ev3dev/wiki/Installation
- put the ev3dev in usb tethering mode. See the instructions at the wiki page https://github.com/ev3dev-python-tools/thonny-ev3dev/wiki/Connect-with-EV3

Finally to put the ev3 in steering mode (remote control from pc) you have to use the ev3rpyc library on the pc. However the library also needs the rpyc server to be installed on the EV3. For instructions see the wiki page https://github.com/ev3dev-python-tools/thonny-ev3dev/wiki/Example#on-the-pc-remotely-steering-the-ev3 .

Good luck,
Harco Kuppens

ps. the whole ev3dev2 should work in steering mode.  However it must be noted that in the current version of the simulator sound is not yet implemented but currently a student is implementing it, so it is expected to work in the next release of the simulator.

**Comment by bemxio** [comment]
thanks for help! i didn't install ev3rpyc, thanks for reminding
